sudo: false

language: node_js
node_js:
  - 8
os:
- linux

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install && npm install

script:
  - npm run lint
  - npm run build

after_success:
  - npm run deploy --token "$FIREBASE_TOKEN"
