sudo: false

language: node_js
node_js:
  - 8
os:
- linux

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - yarn

script:
  - yarn lint
  - yarn build

after_success:
  - echo $FIREBASE_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN --project getlink-frontend --debug
