sudo: false

language: node_js
node_js:
  - 8
os:
- linux

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install && npm install

script:
  - npm run lint
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

deploy:
  provider: firebase
  token:
